"""
Pydantic schemas for Demo Video Pipeline.

Defines models for the storyboard → scene extraction → video asset generation pipeline.
Follows patterns from src/storyboard/schemas.py and src/router/schemas.py.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator

# ============================================================================
# Enums
# ============================================================================


class DemoSceneType(str, Enum):
    """Scene types for demo video pipeline.

    Maps to the 6-scene structure from VideoTemplateManager:
    INTRO (0-15s), PAIN_POINT (15-45s), SOLUTION (45-90s),
    DIFFERENTIATION (90-120s), RESULTS (120-150s), CTA (150-180s).
    """

    INTRO = "intro"
    PAIN_POINT = "pain_point"
    SOLUTION = "solution"
    DIFFERENTIATION = "differentiation"
    RESULTS = "results"
    CTA = "cta"


class DemoPipelineStatus(str, Enum):
    """Status of a demo pipeline job."""

    PENDING = "pending"
    EXTRACTING_SCENES = "extracting_scenes"
    GENERATING_ASSETS = "generating_assets"
    COMPLETED = "completed"
    FAILED = "failed"


# ============================================================================
# Scene Extraction Models
# ============================================================================


# Default timing per scene type (seconds) — from video_template_manager.py
SCENE_TIMING_DEFAULTS: dict[DemoSceneType, dict[str, int]] = {
    DemoSceneType.INTRO: {"start": 0, "end": 15, "duration": 15},
    DemoSceneType.PAIN_POINT: {"start": 15, "end": 45, "duration": 30},
    DemoSceneType.SOLUTION: {"start": 45, "end": 90, "duration": 45},
    DemoSceneType.DIFFERENTIATION: {"start": 90, "end": 120, "duration": 30},
    DemoSceneType.RESULTS: {"start": 120, "end": 150, "duration": 30},
    DemoSceneType.CTA: {"start": 150, "end": 180, "duration": 30},
}

# MVP: 5-second representative clip per scene
MVP_CLIP_DURATION_SECONDS = 5


class SceneTemplate(BaseModel):
    """Single scene with video prompt, timing, and talking points.

    Generated by the SceneExtractorTool from StoryboardUnderstanding data.
    """

    scene_type: DemoSceneType = Field(..., description="Type of scene")
    video_prompt: str = Field(
        ...,
        min_length=10,
        description="Detailed video generation prompt for Kling AI / video provider",
    )
    talking_points: list[str] = Field(
        default_factory=list,
        description="Key talking points for voiceover (2-4 per scene)",
    )
    duration_seconds: int = Field(
        default=MVP_CLIP_DURATION_SECONDS,
        ge=1,
        le=60,
        description="Clip duration in seconds (MVP: 5s per scene)",
    )
    start_time: int = Field(
        default=0, ge=0, description="Start time in full demo timeline (seconds)"
    )
    end_time: int = Field(
        default=0, ge=0, description="End time in full demo timeline (seconds)"
    )
    visual_description: str = Field(
        default="",
        description="Description of the visual content for this scene",
    )

    model_config = {"extra": "forbid"}


class SceneExtractionResult(BaseModel):
    """Collection of 6 SceneTemplates from LLM extraction + metadata."""

    scenes: list[SceneTemplate] = Field(
        ..., min_length=1, max_length=6, description="Extracted scene templates"
    )
    persona: str = Field(
        default="av_director", description="Persona used for extraction"
    )
    vertical: str = Field(
        default="higher_ed", description="Vertical used for extraction"
    )
    product_focus: str = Field(
        default="pearl_mini", description="Product focus for scene prompts"
    )
    model_used: str = Field(
        default="deepseek/deepseek-chat-v3", description="LLM model used for extraction"
    )
    extraction_time_ms: int = Field(
        default=0, ge=0, description="Extraction time in ms"
    )

    model_config = {"extra": "forbid"}


# ============================================================================
# Video Asset Models
# ============================================================================


class VideoAsset(BaseModel):
    """A generated video clip with metadata."""

    scene_type: DemoSceneType = Field(..., description="Scene this clip belongs to")
    scene_name: str = Field(..., description="Human-readable scene name")
    video_url: str | None = Field(
        default=None, description="URL of generated video clip"
    )
    thumbnail_url: str | None = Field(
        default=None, description="URL of video thumbnail"
    )
    duration_seconds: int = Field(
        default=MVP_CLIP_DURATION_SECONDS,
        ge=1,
        description="Clip duration in seconds",
    )
    provider: str = Field(default="kling", description="Video generation provider used")
    estimated_cost_usd: float = Field(
        default=0.0, ge=0.0, description="Estimated generation cost in USD"
    )
    success: bool = Field(default=True, description="Whether generation succeeded")
    error: str | None = Field(
        default=None, description="Error message if generation failed"
    )

    model_config = {"extra": "forbid"}


class VideoAssetBatchResult(BaseModel):
    """Collection of VideoAssets from batch generation."""

    assets: list[VideoAsset] = Field(
        default_factory=list, description="Generated video assets"
    )
    total_scenes: int = Field(default=0, ge=0, description="Total scenes requested")
    successful_scenes: int = Field(
        default=0, ge=0, description="Number of successfully generated scenes"
    )
    failed_scenes: int = Field(
        default=0, ge=0, description="Number of failed scene generations"
    )
    total_estimated_cost_usd: float = Field(
        default=0.0, ge=0.0, description="Total estimated cost in USD"
    )
    provider: str = Field(default="kling", description="Video provider used")

    model_config = {"extra": "forbid"}


# ============================================================================
# Pipeline Job Models
# ============================================================================


class DemoPipelineJob(BaseModel):
    """Internal model for demo pipeline job state (Redis + Supabase).

    Follows StoryboardJob pattern from src/storyboard/schemas.py.
    """

    job_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique job identifier",
    )
    org_id: str = Field(..., description="Organization identifier")
    status: DemoPipelineStatus = Field(
        default=DemoPipelineStatus.PENDING,
        description="Current pipeline status",
    )

    # Input parameters
    understanding: dict[str, Any] = Field(
        default_factory=dict,
        description="StoryboardUnderstanding dict (input to scene extraction)",
    )
    persona: str = Field(default="av_director", description="Target persona")
    vertical: str = Field(default="higher_ed", description="Target vertical")
    product_focus: str = Field(default="pearl_mini", description="Product focus")
    skip_video_generation: bool = Field(
        default=False,
        description="If True, only extract scenes without generating video assets",
    )

    # Output
    scene_extraction: dict[str, Any] | None = Field(
        default=None,
        description="SceneExtractionResult as dict (populated after extraction)",
    )
    video_assets: dict[str, Any] | None = Field(
        default=None,
        description="VideoAssetBatchResult as dict (populated after generation)",
    )
    error_message: str | None = Field(
        default=None, description="Error details if status = 'failed'"
    )

    # Timing
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Job creation timestamp",
    )
    completed_at: datetime | None = Field(
        default=None, description="Job completion timestamp"
    )
    execution_time_ms: int | None = Field(
        default=None, description="Total execution time in milliseconds"
    )

    # Metadata
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata"
    )


# ============================================================================
# API Request / Response Models
# ============================================================================


class DemoPipelineRequest(BaseModel):
    """API request for POST /video/demo-pipeline.

    Three entry points:
    1. understanding dict (from a completed storyboard)
    2. storyboard_job_id (fetch understanding from an existing job)
    3. raw content fields (headline + pain_point + business_value)
    """

    # Entry point 1: Full understanding dict
    understanding: dict[str, Any] | None = Field(
        default=None,
        description="StoryboardUnderstanding dict (from completed storyboard job)",
    )

    # Entry point 2: Reference to existing storyboard job
    storyboard_job_id: str | None = Field(
        default=None,
        description="Job ID of completed storyboard to extract understanding from",
    )

    # Entry point 3: Raw content
    headline: str | None = Field(
        default=None, description="Headline for scene generation"
    )
    pain_point: str | None = Field(
        default=None, description="Pain point to address in scenes"
    )
    business_value: str | None = Field(
        default=None, description="Business value proposition"
    )

    # Common parameters
    persona: str = Field(default="av_director", description="Target persona")
    vertical: str = Field(default="higher_ed", description="Target vertical")
    product_focus: str = Field(default="pearl_mini", description="Product to feature")
    skip_video_generation: bool = Field(
        default=False,
        description="If True, only extract scenes (no video generation). Useful for previewing.",
    )
    provider: str = Field(default="kling", description="Video generation provider")

    model_config = {"extra": "forbid"}

    @field_validator("understanding", mode="before")
    @classmethod
    def validate_has_input(cls, v: dict | None, info: Any) -> dict | None:
        """Ensure at least one input source is provided."""
        return v


class DemoPipelineResponse(BaseModel):
    """API response for POST /video/demo-pipeline (202 Accepted)."""

    job_id: str = Field(..., description="Job ID for polling")
    status: DemoPipelineStatus = Field(..., description="Current job status")
    poll_url: str = Field(..., description="URL to poll for status")

    model_config = {"extra": "forbid"}


class DemoPipelineStatusResponse(BaseModel):
    """API response for GET /video/demo-pipeline/jobs/{job_id}."""

    job_id: str = Field(..., description="Unique job identifier")
    status: DemoPipelineStatus = Field(..., description="Current pipeline status")
    scene_extraction: dict[str, Any] | None = Field(
        default=None, description="Scene extraction result (when available)"
    )
    video_assets: dict[str, Any] | None = Field(
        default=None, description="Video assets result (when available)"
    )
    error_message: str | None = Field(
        default=None, description="Error message (when failed)"
    )
    execution_time_ms: int | None = Field(
        default=None, description="Total execution time in ms"
    )
    created_at: datetime = Field(..., description="Job creation timestamp")
    completed_at: datetime | None = Field(
        default=None, description="Job completion timestamp"
    )

    model_config = {"extra": "forbid"}
