-- Epiphan Storyboard Router Jobs SQL Migration
-- Run in Supabase SQL Editor
-- Created: 2025-12-24
-- Purpose: Async agent router jobs with Redis hot state + PostgreSQL persistence

-- =============================================================================
-- ROUTER_JOBS TABLE
-- Stores async router jobs (classify + route + execute)
-- =============================================================================

CREATE TABLE IF NOT EXISTS router_jobs (
    -- Identification
    job_id TEXT PRIMARY KEY,  -- UUID generated by application
    org_id TEXT NOT NULL,  -- Multi-tenant organization identifier

    -- Job configuration
    query TEXT NOT NULL,  -- User query to classify and route
    context JSONB DEFAULT '{}'::jsonb,  -- Optional context for classification
    max_steps INTEGER DEFAULT 10,  -- Maximum execution steps

    -- Status tracking
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
        'pending',      -- Job created, waiting to start
        'classifying',  -- Running task classification
        'routing',      -- Selecting appropriate chain
        'executing',    -- Executing the chain
        'completed',    -- Successfully completed
        'failed',       -- Failed with error
        'cancelled'     -- Cancelled by user/system
    )),

    -- Classification result (from TaskClassifier)
    classification JSONB,  -- {task_type, confidence, reasoning, extracted_params, recommended_model}

    -- Chain execution result
    chain_result JSONB,  -- Result from chain execution
    error_message TEXT,  -- Error details if status = 'failed'

    -- Timing
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,  -- When job finished (success or failure)
    execution_time_ms INTEGER  -- Total execution time in milliseconds
);

-- =============================================================================
-- INDEXES
-- Optimized for common query patterns
-- =============================================================================

-- Multi-tenant queries (most common access pattern)
CREATE INDEX IF NOT EXISTS idx_router_jobs_org_id ON router_jobs(org_id);

-- Status monitoring (find pending/failed jobs)
CREATE INDEX IF NOT EXISTS idx_router_jobs_status ON router_jobs(status) WHERE status IN ('pending', 'executing', 'failed');

-- Recent jobs listing (sorted by created_at DESC)
CREATE INDEX IF NOT EXISTS idx_router_jobs_created ON router_jobs(created_at DESC);

-- Task type analytics (on JSONB path)
CREATE INDEX IF NOT EXISTS idx_router_jobs_task_type ON router_jobs((classification->>'task_type')) WHERE classification IS NOT NULL;

-- Composite index for org + status queries (efficient tenant-specific monitoring)
CREATE INDEX IF NOT EXISTS idx_router_jobs_org_status ON router_jobs(org_id, status);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- API-only access via service role
-- =============================================================================

ALTER TABLE router_jobs ENABLE ROW LEVEL SECURITY;

-- Service role has full access (backend bypass RLS)
CREATE POLICY IF NOT EXISTS "Service role full access router_jobs"
    ON router_jobs FOR ALL
    USING (auth.role() = 'service_role');

-- No public access - API-only
-- (No policies for anon/authenticated users means they get zero access)

-- =============================================================================
-- HELPER VIEWS
-- Convenient views for monitoring and analytics
-- =============================================================================

-- Recent jobs: Last 100 jobs with key fields
CREATE OR REPLACE VIEW recent_router_jobs AS
SELECT
    job_id,
    org_id,
    status,
    classification->>'task_type' as task_type,
    (classification->>'confidence')::FLOAT as confidence,
    CASE
        WHEN chain_result->>'success' = 'true' THEN true
        ELSE false
    END as chain_success,
    created_at,
    completed_at,
    execution_time_ms,
    CASE
        WHEN error_message IS NOT NULL THEN SUBSTRING(error_message, 1, 100)
        ELSE NULL
    END as error_preview
FROM router_jobs
ORDER BY created_at DESC
LIMIT 100;

-- Job stats: Aggregated success/failure rates by task_type
CREATE OR REPLACE VIEW router_job_stats AS
SELECT
    classification->>'task_type' as task_type,
    COUNT(*) as total_jobs,
    COUNT(*) FILTER (WHERE status = 'completed') as completed,
    COUNT(*) FILTER (WHERE status = 'failed') as failed,
    COUNT(*) FILTER (WHERE status IN ('pending', 'classifying', 'routing', 'executing')) as in_progress,
    ROUND(
        (COUNT(*) FILTER (WHERE status = 'completed')::NUMERIC / NULLIF(COUNT(*), 0)) * 100,
        2
    ) as success_rate_pct,
    ROUND(AVG((classification->>'confidence')::FLOAT) FILTER (WHERE classification IS NOT NULL), 3) as avg_confidence,
    ROUND(AVG(execution_time_ms) FILTER (WHERE status = 'completed'), 0) as avg_execution_ms,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY execution_time_ms) FILTER (WHERE status = 'completed') as median_execution_ms,
    MAX(execution_time_ms) FILTER (WHERE status = 'completed') as max_execution_ms
FROM router_jobs
WHERE created_at > NOW() - INTERVAL '30 days'  -- Last 30 days only
GROUP BY classification->>'task_type'
ORDER BY total_jobs DESC;

-- Organization usage: Jobs per org (for billing/quota monitoring)
CREATE OR REPLACE VIEW router_org_usage AS
SELECT
    org_id,
    COUNT(*) as total_jobs,
    COUNT(*) FILTER (WHERE status = 'completed') as successful_jobs,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_jobs,
    COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '24 hours') as jobs_last_24h,
    COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '7 days') as jobs_last_7d,
    MAX(created_at) as last_job_at,
    ROUND(AVG(execution_time_ms) FILTER (WHERE status = 'completed'), 0) as avg_execution_ms
FROM router_jobs
GROUP BY org_id
ORDER BY total_jobs DESC;

-- Failed jobs: Recent failures for debugging
CREATE OR REPLACE VIEW router_failures AS
SELECT
    job_id,
    org_id,
    classification->>'task_type' as task_type,
    query,
    created_at,
    completed_at,
    execution_time_ms,
    error_message,
    context,
    classification,
    chain_result
FROM router_jobs
WHERE status = 'failed'
ORDER BY created_at DESC
LIMIT 50;

-- Classification analytics: Confidence distribution by task type
CREATE OR REPLACE VIEW router_classification_analytics AS
SELECT
    classification->>'task_type' as task_type,
    COUNT(*) as total_classifications,
    ROUND(AVG((classification->>'confidence')::FLOAT), 3) as avg_confidence,
    ROUND(MIN((classification->>'confidence')::FLOAT), 3) as min_confidence,
    ROUND(MAX((classification->>'confidence')::FLOAT), 3) as max_confidence,
    COUNT(*) FILTER (WHERE (classification->>'confidence')::FLOAT >= 0.9) as high_confidence_count,
    COUNT(*) FILTER (WHERE (classification->>'confidence')::FLOAT >= 0.7 AND (classification->>'confidence')::FLOAT < 0.9) as medium_confidence_count,
    COUNT(*) FILTER (WHERE (classification->>'confidence')::FLOAT < 0.7) as low_confidence_count
FROM router_jobs
WHERE classification IS NOT NULL
  AND created_at > NOW() - INTERVAL '30 days'
GROUP BY classification->>'task_type'
ORDER BY total_classifications DESC;

-- =============================================================================
-- GRANT PERMISSIONS
-- =============================================================================

GRANT ALL ON router_jobs TO service_role;
GRANT SELECT ON recent_router_jobs TO service_role;
GRANT SELECT ON router_job_stats TO service_role;
GRANT SELECT ON router_org_usage TO service_role;
GRANT SELECT ON router_failures TO service_role;
GRANT SELECT ON router_classification_analytics TO service_role;

-- =============================================================================
-- SUCCESS MESSAGE
-- =============================================================================

DO $$
BEGIN
    RAISE NOTICE '✓ Router Jobs SQL migration completed successfully!';
    RAISE NOTICE '  - Table created: router_jobs';
    RAISE NOTICE '  - Indexes: 5 indexes for org_id, status, created_at, task_type, composite';
    RAISE NOTICE '  - Views: recent_router_jobs, router_job_stats, router_org_usage, router_failures, router_classification_analytics';
    RAISE NOTICE '  - RLS: Enabled with service_role-only access (API-only)';
    RAISE NOTICE '';
    RAISE NOTICE 'Next steps:';
    RAISE NOTICE '  1. Verify table: SELECT * FROM router_jobs LIMIT 1;';
    RAISE NOTICE '  2. Check views: SELECT * FROM router_job_stats;';
    RAISE NOTICE '  3. Test via API: POST /agents/route with {"query": "scrape example.com"}';
END $$;
